#import "LocalizationManager.h"

NSString * const kLanguageChangedNotification = @"LanguageChangedNotification";

/// Macro: chiama singleton ogni volta (abbastanza leggero)
NSString* LOC(NSString *key) {
    return [[LocalizationManager shared] stringForKey:key];
}

@interface LocalizationManager ()
@property (nonatomic,strong) NSDictionary<NSString*,NSDictionary<NSString*,NSString*>*> *tables;
@end

@implementation LocalizationManager

+ (instancetype)shared {
    static LocalizationManager *instance = nil;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{ instance = [[LocalizationManager alloc] init]; });
    return instance;
}

- (instancetype)init {
    if (self = [super init]) {
        _currentLanguage = AppLanguageItalian;
        [self buildTranslationTables];
    }
    return self;
}

- (void)buildTranslationTables {
    // IT = chiavi originali (default), EN, FR, DE, ES
    // Ogni lingua ha lo stesso set di chiavi con la traduzione
    _tables = @{
        @"it": [self italianTable],
        @"en": [self englishTable],
        @"fr": [self frenchTable],
        @"de": [self germanTable],
        @"es": [self spanishTable],
    };
}

#pragma mark - Public API

- (NSString*)stringForKey:(NSString*)key {
    NSString *code = [self languageCode];
    NSDictionary *table = _tables[code];
    NSString *val = table[key];
    return val ?: key; // fallback: mostra la chiave stessa
}

- (void)setLanguage:(AppLanguage)lang {
    if (_currentLanguage == lang) return;
    _currentLanguage = lang;
    [[NSUserDefaults standardUserDefaults] setInteger:lang forKey:@"app_language"];
    [[NSUserDefaults standardUserDefaults] synchronize];
    [[NSNotificationCenter defaultCenter] postNotificationName:kLanguageChangedNotification object:nil];
}

- (NSArray<NSString*>*)availableLanguageNames {
    return @[@"Italiano", @"English", @"Français", @"Deutsch", @"Español"];
}

- (NSString*)languageNameForCode:(AppLanguage)lang {
    switch (lang) {
        case AppLanguageItalian: return @"Italiano";
        case AppLanguageEnglish: return @"English";
        case AppLanguageFrench:  return @"Français";
        case AppLanguageGerman:  return @"Deutsch";
        case AppLanguageSpanish: return @"Español";
    }
}

- (AppLanguage)languageCodeForName:(NSString*)name {
    if ([name isEqualToString:@"English"])   return AppLanguageEnglish;
    if ([name isEqualToString:@"Français"])  return AppLanguageFrench;
    if ([name isEqualToString:@"Deutsch"])   return AppLanguageGerman;
    if ([name isEqualToString:@"Español"])   return AppLanguageSpanish;
    return AppLanguageItalian;
}

- (NSString*)languageCode {
    switch (_currentLanguage) {
        case AppLanguageItalian: return @"it";
        case AppLanguageEnglish: return @"en";
        case AppLanguageFrench:  return @"fr";
        case AppLanguageGerman:  return @"de";
        case AppLanguageSpanish: return @"es";
    }
}

#pragma mark - Translation Tables

- (NSDictionary*)italianTable { return @{}; } // italiano = chiave stessa

- (NSDictionary*)englishTable { return @{
    // ── Sezioni ──
    @"NAVIGAZIONE": @"NAVIGATION",
    @"MAPPA": @"MAP",
    @"AVVISI": @"ALERTS",
    @"SISTEMA": @"SYSTEM",
    @"SCHERMO": @"DISPLAY",
    @"Navigazione": @"Navigation",
    @"Mappa": @"Map",
    @"Avvisi": @"Alerts",
    @"Sistema": @"System",
    @"Schermo": @"Display",
    @"Impostazioni": @"Settings",
    // ── Navigazione ──
    @"Modalità": @"Mode",
    @"Percorso preferito": @"Preferred Route",
    @"Evitare pedaggi": @"Avoid Tolls",
    @"Evitare autostrade": @"Avoid Highways",
    @"Evitare traghetti": @"Avoid Ferries",
    @"Ricalcolo automatico": @"Auto Reroute",
    @"Mostra alternative": @"Show Alternatives",
    @"Indicazioni vocali": @"Voice Guidance",
    @"Volume guida": @"Guidance Volume",
    @"Traffico in tempo reale": @"Live Traffic",
    @"POI lungo il percorso": @"POI Along Route",
    @"Avviso autovelox": @"Speed Camera Alert",
    @"Velocità corrente": @"Current Speed",
    @"Navigazione offline": @"Offline Navigation",
    @"Voci": @"Voices",
    @"Auto": @"Car",
    @"Autobus": @"Bus",
    @"Camion": @"Truck",
    @"Più veloce": @"Fastest",
    @"Più breve": @"Shortest",
    @"Eco": @"Eco",
    // ── Mappa ──
    @"Tipo mappa": @"Map Type",
    @"Standard": @"Standard",
    @"Satellite": @"Satellite",
    @"Hybrid": @"Hybrid",
    @"Vista 3D predefinita": @"Default 3D View",
    @"Attiva": @"On",
    @"Disattiva": @"Off",
    @"Mostra edifici 3D": @"Show 3D Buildings",
    @"Mostra traffico": @"Show Traffic",
    @"Modalità notturna": @"Night Mode",
    @"Zoom automatico": @"Auto Zoom",
    @"Orientamento mappa": @"Map Orientation",
    @"Nord in alto": @"North Up",
    @"Rotta in alto": @"Heading Up",
    @"Mostra bussola": @"Show Compass",
    @"Mostra scala": @"Show Scale",
    @"Etichette POI": @"POI Labels",
    @"Tutte": @"All",
    @"Nessuna": @"None",
    @"Solo principali": @"Main Only",
    // ── Avvisi ──
    @"Livello avvisi": @"Alert Level",
    @"No avvisi": @"No Alerts",
    @"Avvisi importanti": @"Important Alerts",
    @"Avvisi completi": @"Full Alerts",
    @"Limite velocità": @"Speed Limit",
    @"Autovelox fisso": @"Fixed Camera",
    @"Autovelox mobile": @"Mobile Camera",
    @"Incidenti": @"Accidents",
    @"Lavori in corso": @"Roadworks",
    @"Strade chiuse": @"Closed Roads",
    @"Condizioni meteo": @"Weather",
    @"Pericolo ghiaccio": @"Ice Hazard",
    @"Zona scolastica": @"School Zone",
    // ── Sistema ──
    @"Unità di misura": @"Units",
    @"Metrico": @"Metric",
    @"Imperiale": @"Imperial",
    @"Lingua": @"Language",
    @"Italiano": @"Italian",
    @"Feedback aptico": @"Haptic Feedback",
    @"Risparmio batteria": @"Battery Saver",
    @"Cache mappe": @"Map Cache",
    @"Privacy & dati": @"Privacy & Data",
    @"Licenze open source": @"Open Source Licenses",
    @"Info su Autista": @"About Autista",
    // ── Schermo ──
    @"Luminosità automatica": @"Auto Brightness",
    @"Tema scuro": @"Dark Theme",
    @"Dimensione testo": @"Text Size",
    @"Normale": @"Normal",
    @"Grande": @"Large",
    @"Molto grande": @"Very Large",
    @"Mostra tachimetro": @"Show Speedometer",
    @"Mostra ETA": @"Show ETA",
    @"Barra stato trasparente": @"Transparent Status Bar",
    @"Animazioni ridotte": @"Reduced Animations",
    @"Always-on display": @"Always-On Display",
    // ── Schermo slider ──
    @"📷 Camera 3D": @"📷 3D Camera",
    @"Altezza": @"Altitude",
    @"Angolazione": @"Angle",
    @"Destra/Sinistra": @"Right/Left",
    @"Tilt visuale": @"Visual Tilt",
    @"🎨 Temi": @"🎨 Themes",
    @"Trasparenza": @"Opacity",
    @"Vetro": @"Glass",
    @"Pieno": @"Solid",
    @"Riflesso vetro": @"Glass Reflection",
    @"Tinta calda/fredda": @"Warm/Cool Tint",
    @"Calda": @"Warm",
    @"Neutra": @"Neutral",
    @"Fredda": @"Cool",
    @"Spessore bordo": @"Border Thickness",
    @"Sottile": @"Thin",
    @"Spesso": @"Thick",
    @"Luminosità": @"Brightness",
    @"Bassa": @"Low",
    @"Alta": @"High",
    @"Ingrand. testo": @"Text Scale",

    @"Trasparente": @"Transparent",
    @"Opaco": @"Opaque",
    @"Opacità sfondo": @"Background Opacity",
    @"Niente": @"None",
    @"Scuro": @"Dark",
    @"Chiara": @"Light",
    @"Scura": @"Dark",
};}

- (NSDictionary*)frenchTable { return @{
    @"NAVIGAZIONE": @"NAVIGATION",
    @"MAPPA": @"CARTE",
    @"AVVISI": @"ALERTES",
    @"SISTEMA": @"SYSTÈME",
    @"SCHERMO": @"AFFICHAGE",
    @"Navigazione": @"Navigation",
    @"Mappa": @"Carte",
    @"Avvisi": @"Alertes",
    @"Sistema": @"Système",
    @"Schermo": @"Affichage",
    @"Impostazioni": @"Paramètres",
    @"Modalità": @"Mode",
    @"Percorso preferito": @"Itinéraire préféré",
    @"Evitare pedaggi": @"Éviter péages",
    @"Evitare autostrade": @"Éviter autoroutes",
    @"Evitare traghetti": @"Éviter ferries",
    @"Ricalcolo automatico": @"Recalcul automatique",
    @"Mostra alternative": @"Afficher alternatives",
    @"Indicazioni vocali": @"Guidage vocal",
    @"Volume guida": @"Volume guidage",
    @"Traffico in tempo reale": @"Trafic en direct",
    @"POI lungo il percorso": @"POI sur le parcours",
    @"Avviso autovelox": @"Alerte radar",
    @"Velocità corrente": @"Vitesse actuelle",
    @"Navigazione offline": @"Navigation hors-ligne",
    @"Voci": @"Voix",
    @"Auto": @"Voiture",
    @"Autobus": @"Bus",
    @"Camion": @"Camion",
    @"Più veloce": @"Le plus rapide",
    @"Più breve": @"Le plus court",
    @"Eco": @"Éco",
    @"Tipo mappa": @"Type de carte",
    @"Standard": @"Standard",
    @"Satellite": @"Satellite",
    @"Hybrid": @"Hybride",
    @"Vista 3D predefinita": @"Vue 3D par défaut",
    @"Attiva": @"Activé",
    @"Disattiva": @"Désactivé",
    @"Mostra edifici 3D": @"Bâtiments 3D",
    @"Mostra traffico": @"Afficher trafic",
    @"Modalità notturna": @"Mode nuit",
    @"Zoom automatico": @"Zoom auto",
    @"Orientamento mappa": @"Orientation carte",
    @"Nord in alto": @"Nord en haut",
    @"Rotta in alto": @"Cap en haut",
    @"Mostra bussola": @"Boussole",
    @"Mostra scala": @"Échelle",
    @"Etichette POI": @"Étiquettes POI",
    @"Tutte": @"Toutes",
    @"Nessuna": @"Aucune",
    @"Solo principali": @"Principales",
    @"Livello avvisi": @"Niveau d'alertes",
    @"No avvisi": @"Aucune alerte",
    @"Avvisi importanti": @"Alertes importantes",
    @"Avvisi completi": @"Alertes complètes",
    @"Limite velocità": @"Limite vitesse",
    @"Autovelox fisso": @"Radar fixe",
    @"Autovelox mobile": @"Radar mobile",
    @"Incidenti": @"Accidents",
    @"Lavori in corso": @"Travaux",
    @"Strade chiuse": @"Routes fermées",
    @"Condizioni meteo": @"Météo",
    @"Pericolo ghiaccio": @"Verglas",
    @"Zona scolastica": @"Zone scolaire",
    @"Unità di misura": @"Unités",
    @"Metrico": @"Métrique",
    @"Imperiale": @"Impérial",
    @"Lingua": @"Langue",
    @"Italiano": @"Italien",
    @"Feedback aptico": @"Retour haptique",
    @"Risparmio batteria": @"Économie batterie",
    @"Cache mappe": @"Cache cartes",
    @"Privacy & dati": @"Confidentialité",
    @"Licenze open source": @"Licences open source",
    @"Info su Autista": @"À propos d'Autista",
    @"Luminosità automatica": @"Luminosité auto",
    @"Tema scuro": @"Thème sombre",
    @"Dimensione testo": @"Taille texte",
    @"Normale": @"Normal",
    @"Grande": @"Grand",
    @"Molto grande": @"Très grand",
    @"Mostra tachimetro": @"Compteur vitesse",
    @"Mostra ETA": @"Afficher ETA",
    @"Barra stato trasparente": @"Barre transparente",
    @"Animazioni ridotte": @"Animations réduites",
    @"Always-on display": @"Écran permanent",
    @"📷 Camera 3D": @"📷 Caméra 3D",
    @"Altezza": @"Altitude",
    @"Angolazione": @"Angle",
    @"Destra/Sinistra": @"Droite/Gauche",
    @"Tilt visuale": @"Inclinaison",
    @"🎨 Temi": @"🎨 Thèmes",
    @"Trasparenza": @"Transparence",
    @"Vetro": @"Verre",
    @"Pieno": @"Solide",
    @"Riflesso vetro": @"Reflet vitre",
    @"Tinta calda/fredda": @"Teinte chaud/froid",
    @"Calda": @"Chaud",
    @"Neutra": @"Neutre",
    @"Fredda": @"Froid",
    @"Spessore bordo": @"Épaisseur bordure",
    @"Sottile": @"Fin",
    @"Spesso": @"Épais",
    @"Luminosità": @"Luminosité",
    @"Bassa": @"Basse",
    @"Alta": @"Haute",
    @"Ingrand. testo": @"Échelle texte",

    @"Trasparente": @"Transparent",
    @"Opaco": @"Opaque",
    @"Opacità sfondo": @"Opacité fond",
    @"Niente": @"Rien",
    @"Scuro": @"Sombre",
    @"Chiara": @"Clair",
    @"Scura": @"Sombre",
};}

- (NSDictionary*)germanTable { return @{
    @"NAVIGAZIONE": @"NAVIGATION",
    @"MAPPA": @"KARTE",
    @"AVVISI": @"WARNUNGEN",
    @"SISTEMA": @"SYSTEM",
    @"SCHERMO": @"ANZEIGE",
    @"Navigazione": @"Navigation",
    @"Mappa": @"Karte",
    @"Avvisi": @"Warnungen",
    @"Sistema": @"System",
    @"Schermo": @"Anzeige",
    @"Impostazioni": @"Einstellungen",
    @"Modalità": @"Modus",
    @"Percorso preferito": @"Bevorzugte Route",
    @"Evitare pedaggi": @"Maut vermeiden",
    @"Evitare autostrade": @"Autobahnen meiden",
    @"Evitare traghetti": @"Fähren meiden",
    @"Ricalcolo automatico": @"Auto-Neuberechnung",
    @"Mostra alternative": @"Alternativen zeigen",
    @"Indicazioni vocali": @"Sprachführung",
    @"Volume guida": @"Lautstärke Führung",
    @"Traffico in tempo reale": @"Live-Verkehr",
    @"POI lungo il percorso": @"POI entlang Route",
    @"Avviso autovelox": @"Blitzer-Warnung",
    @"Velocità corrente": @"Aktuelle Geschw.",
    @"Navigazione offline": @"Offline-Navigation",
    @"Voci": @"Stimmen",
    @"Auto": @"Auto",
    @"Autobus": @"Bus",
    @"Camion": @"LKW",
    @"Più veloce": @"Schnellste",
    @"Più breve": @"Kürzeste",
    @"Eco": @"Öko",
    @"Tipo mappa": @"Kartentyp",
    @"Standard": @"Standard",
    @"Satellite": @"Satellit",
    @"Hybrid": @"Hybrid",
    @"Vista 3D predefinita": @"Standard 3D-Ansicht",
    @"Attiva": @"An",
    @"Disattiva": @"Aus",
    @"Mostra edifici 3D": @"3D-Gebäude",
    @"Mostra traffico": @"Verkehr anzeigen",
    @"Modalità notturna": @"Nachtmodus",
    @"Zoom automatico": @"Auto-Zoom",
    @"Orientamento mappa": @"Kartenausrichtung",
    @"Nord in alto": @"Norden oben",
    @"Rotta in alto": @"Kurs oben",
    @"Mostra bussola": @"Kompass",
    @"Mostra scala": @"Maßstab",
    @"Etichette POI": @"POI-Beschriftung",
    @"Tutte": @"Alle",
    @"Nessuna": @"Keine",
    @"Solo principali": @"Nur wichtige",
    @"Livello avvisi": @"Warnstufe",
    @"No avvisi": @"Keine Warnungen",
    @"Avvisi importanti": @"Wichtige Warnungen",
    @"Avvisi completi": @"Alle Warnungen",
    @"Limite velocità": @"Tempolimit",
    @"Autovelox fisso": @"Fester Blitzer",
    @"Autovelox mobile": @"Mobiler Blitzer",
    @"Incidenti": @"Unfälle",
    @"Lavori in corso": @"Baustellen",
    @"Strade chiuse": @"Straßensperren",
    @"Condizioni meteo": @"Wetter",
    @"Pericolo ghiaccio": @"Glatteis",
    @"Zona scolastica": @"Schulzone",
    @"Unità di misura": @"Einheiten",
    @"Metrico": @"Metrisch",
    @"Imperiale": @"Imperial",
    @"Lingua": @"Sprache",
    @"Italiano": @"Italienisch",
    @"Feedback aptico": @"Haptisches Feedback",
    @"Risparmio batteria": @"Energiesparmodus",
    @"Cache mappe": @"Karten-Cache",
    @"Privacy & dati": @"Datenschutz",
    @"Licenze open source": @"Open-Source-Lizenzen",
    @"Info su Autista": @"Über Autista",
    @"Luminosità automatica": @"Auto-Helligkeit",
    @"Tema scuro": @"Dunkles Thema",
    @"Dimensione testo": @"Textgröße",
    @"Normale": @"Normal",
    @"Grande": @"Groß",
    @"Molto grande": @"Sehr groß",
    @"Mostra tachimetro": @"Tachometer",
    @"Mostra ETA": @"ETA anzeigen",
    @"Barra stato trasparente": @"Transparente Leiste",
    @"Animazioni ridotte": @"Reduzierte Animation",
    @"Always-on display": @"Always-On Display",
    @"📷 Camera 3D": @"📷 3D-Kamera",
    @"Altezza": @"Höhe",
    @"Angolazione": @"Winkel",
    @"Destra/Sinistra": @"Rechts/Links",
    @"Tilt visuale": @"Neigung",
    @"🎨 Temi": @"🎨 Themen",
    @"Trasparenza": @"Transparenz",
    @"Vetro": @"Glas",
    @"Pieno": @"Massiv",
    @"Riflesso vetro": @"Glasreflexion",
    @"Tinta calda/fredda": @"Warm/Kalt-Tönung",
    @"Calda": @"Warm",
    @"Neutra": @"Neutral",
    @"Fredda": @"Kalt",
    @"Spessore bordo": @"Randdicke",
    @"Sottile": @"Dünn",
    @"Spesso": @"Dick",
    @"Luminosità": @"Helligkeit",
    @"Bassa": @"Niedrig",
    @"Alta": @"Hoch",
    @"Ingrand. testo": @"Textskalierung",

    @"Trasparente": @"Transparent",
    @"Opaco": @"Blickdicht",
    @"Opacità sfondo": @"Hintergrund-Deckkraft",
    @"Niente": @"Nichts",
    @"Scuro": @"Dunkel",
    @"Chiara": @"Hell",
    @"Scura": @"Dunkel",
};}

- (NSDictionary*)spanishTable { return @{
    @"NAVIGAZIONE": @"NAVEGACIÓN",
    @"MAPPA": @"MAPA",
    @"AVVISI": @"ALERTAS",
    @"SISTEMA": @"SISTEMA",
    @"SCHERMO": @"PANTALLA",
    @"Navigazione": @"Navegación",
    @"Mappa": @"Mapa",
    @"Avvisi": @"Alertas",
    @"Sistema": @"Sistema",
    @"Schermo": @"Pantalla",
    @"Impostazioni": @"Configuración",
    @"Modalità": @"Modo",
    @"Percorso preferito": @"Ruta preferida",
    @"Evitare pedaggi": @"Evitar peajes",
    @"Evitare autostrade": @"Evitar autopistas",
    @"Evitare traghetti": @"Evitar ferris",
    @"Ricalcolo automatico": @"Recálculo automático",
    @"Mostra alternative": @"Mostrar alternativas",
    @"Indicazioni vocali": @"Guía por voz",
    @"Volume guida": @"Volumen guía",
    @"Traffico in tempo reale": @"Tráfico en directo",
    @"POI lungo il percorso": @"POI en ruta",
    @"Avviso autovelox": @"Aviso radar",
    @"Velocità corrente": @"Velocidad actual",
    @"Navigazione offline": @"Navegación sin conexión",
    @"Voci": @"Voces",
    @"Auto": @"Coche",
    @"Autobus": @"Autobús",
    @"Camion": @"Camión",
    @"Più veloce": @"Más rápida",
    @"Più breve": @"Más corta",
    @"Eco": @"Eco",
    @"Tipo mappa": @"Tipo de mapa",
    @"Standard": @"Estándar",
    @"Satellite": @"Satélite",
    @"Hybrid": @"Híbrido",
    @"Vista 3D predefinita": @"Vista 3D por defecto",
    @"Attiva": @"Activado",
    @"Disattiva": @"Desactivado",
    @"Mostra edifici 3D": @"Edificios 3D",
    @"Mostra traffico": @"Mostrar tráfico",
    @"Modalità notturna": @"Modo noche",
    @"Zoom automatico": @"Zoom automático",
    @"Orientamento mappa": @"Orientación mapa",
    @"Nord in alto": @"Norte arriba",
    @"Rotta in alto": @"Rumbo arriba",
    @"Mostra bussola": @"Brújula",
    @"Mostra scala": @"Escala",
    @"Etichette POI": @"Etiquetas POI",
    @"Tutte": @"Todas",
    @"Nessuna": @"Ninguna",
    @"Solo principali": @"Solo principales",
    @"Livello avvisi": @"Nivel de alertas",
    @"No avvisi": @"Sin alertas",
    @"Avvisi importanti": @"Alertas importantes",
    @"Avvisi completi": @"Alertas completas",
    @"Limite velocità": @"Límite velocidad",
    @"Autovelox fisso": @"Radar fijo",
    @"Autovelox mobile": @"Radar móvil",
    @"Incidenti": @"Accidentes",
    @"Lavori in corso": @"Obras",
    @"Strade chiuse": @"Vías cerradas",
    @"Condizioni meteo": @"Clima",
    @"Pericolo ghiaccio": @"Hielo",
    @"Zona scolastica": @"Zona escolar",
    @"Unità di misura": @"Unidades",
    @"Metrico": @"Métrico",
    @"Imperiale": @"Imperial",
    @"Lingua": @"Idioma",
    @"Italiano": @"Italiano",
    @"Feedback aptico": @"Respuesta háptica",
    @"Risparmio batteria": @"Ahorro batería",
    @"Cache mappe": @"Caché mapas",
    @"Privacy & dati": @"Privacidad y datos",
    @"Licenze open source": @"Licencias open source",
    @"Info su Autista": @"Acerca de Autista",
    @"Luminosità automatica": @"Brillo automático",
    @"Tema scuro": @"Tema oscuro",
    @"Dimensione testo": @"Tamaño texto",
    @"Normale": @"Normal",
    @"Grande": @"Grande",
    @"Molto grande": @"Muy grande",
    @"Mostra tachimetro": @"Velocímetro",
    @"Mostra ETA": @"Mostrar ETA",
    @"Barra stato trasparente": @"Barra transparente",
    @"Animazioni ridotte": @"Animaciones reducidas",
    @"Always-on display": @"Pantalla siempre activa",
    @"📷 Camera 3D": @"📷 Cámara 3D",
    @"Altezza": @"Altitud",
    @"Angolazione": @"Ángulo",
    @"Destra/Sinistra": @"Derecha/Izquierda",
    @"Tilt visuale": @"Inclinación",
    @"🎨 Temi": @"🎨 Temas",
    @"Trasparenza": @"Transparencia",
    @"Vetro": @"Cristal",
    @"Pieno": @"Sólido",
    @"Riflesso vetro": @"Reflejo cristal",
    @"Tinta calda/fredda": @"Tinte cálido/frío",
    @"Calda": @"Cálido",
    @"Neutra": @"Neutro",
    @"Fredda": @"Frío",
    @"Spessore bordo": @"Grosor borde",
    @"Sottile": @"Fino",
    @"Spesso": @"Grueso",
    @"Luminosità": @"Brillo",
    @"Bassa": @"Bajo",
    @"Alta": @"Alto",
    @"Ingrand. testo": @"Escala texto",

    @"Trasparente": @"Transparente",
    @"Opaco": @"Opaco",
    @"Opacità sfondo": @"Opacidad fondo",
    @"Niente": @"Nada",
    @"Scuro": @"Oscuro",
    @"Chiara": @"Claro",
    @"Scura": @"Oscuro",
};}

@end
